### ISSUE TITLE
How about use go-dockerclient ?

### ISSUE THREAD

**Issue by clongbupt** [ory-am/dockertest#11]
Just found this repo, it is easy to do a integration test with postgres for golang project.

How about using some golang dockerclient instead of wrapping docker cli and parsing byte output ?

- [go-dockerclient](https://github.com/fsouza/go-dockerclient)
- [dockerclient](https://github.com/samalba/dockerclient)

**Comment by arekkas** [comment]
Good point, `docker-machine` unfortunately has no go bindings yet which is why this was originally written using the CLI. However it might be smarter to detect if `docker-machine` is available, boot it and pass the env vars to *go-dockerclient* or *dockerclient*.

The reason why this has not been done yet is because of the adaptation of camlistores dockertest implementation, which uses the CLI as well.

If no issues arise from using the CLI instead of bindings/APIs, I'd flag this as nice-to-have/low-prio. Do you agree?

**Comment by clongbupt** [comment]
Okk.

**Comment by arekkas** [comment]
Cool, thanks for bringing your thoughts to the project!

**Comment by arekkas** [comment]
You can now do this with https://github.com/ory-am/dockertest/pull/46 and following
