### ISSUE TITLE
Did not figure out how to use the NSQ functions

### ISSUE THREAD

**Issue by ggeorgiev** [ory-am/dockertest#48]
Do you have an example how to run connect NSQLookup and the NSQd? Just running them both does not seem to does it.

**Comment by arekkas** [comment]
Hey i will reply when im back from vacation next week

Gesendet mit meinem HTC

----- Reply message -----
Von: "George" <notifications@github.com>
An: "ory-am/dockertest" <dockertest@noreply.github.com>
Betreff: [ory-am/dockertest] Did not figure out how to use the NSQ functions (#48)
Datum: Fr., Mai 20, 2016 22:27

Do you have an example how to run connect NSQLookup and the NSQd? Just running them both does not seem to does it.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/ory-am/dockertest/issues/48

**Comment by arekkas** [comment]
Did you look at the example: https://github.com/ory-am/dockertest/blob/master/docker_integration_test.go#L183 ?

**Comment by ggeorgiev** [comment]
yes. This runs the one ... and the other. But they are useful only of NSQd is hooked in the NSQLookupd.

**Comment by arekkas** [comment]
Ah I see, maybe this will suit you better: https://github.com/ibrt/go-compose

**Comment by arekkas** [comment]
closed because a better alternative for this use case exists
