### ISSUE TITLE
Not working for the newest docker beta for Mac OS

### ISSUE THREAD

**Issue by jaggerwang** [ory-am/dockertest#51]
It complains "Starting docker machine "default" failed". The new docker no need virtualbox anymore.

**Comment by arekkas** [comment]
Can you please post which version that is exactly and a link to it?

**Comment by jaggerwang** [comment]
![image](https://cloud.githubusercontent.com/assets/1255011/16171640/ab8daeea-35a6-11e6-824a-8bd21dfd603e.png)

https://beta.docker.com/，download need to be invited. I've already get through by create a virtualbox machine, as the old way.

**Comment by arekkas** [comment]
cool, thanks for the links. docker is really moving forward. i will introduce a way to have both docker-machine and docker "native" work, but i will wait for a stable release. if you want you can give it a shot too and ask if you need help!

**Comment by manuel-huez** [comment]
Yup, need that as well!

**Comment by arekkas** [comment]
If you remove `docker-machine` from your environment, you should be good to go.

**Comment by mhurne** [comment]
It might be something strange on my system, but I _think_ Docker for Mac (rather than Docker Toolbox) installs `docker-machine`. No idea why, but if I `rm /usr/local/bin/docker-machine` and then restart Docker for Mac, `/usr/local/bin/docker-machine` exists after Docker for Mac starts back up. Then dockertest tries to use `docker-machine` when my tests run, and they fail because I don't have a docker machine named "default" (because I don't want to use docker machine, of course).

**Comment by arekkas** [comment]
that's really weird. could you maybe open an issue in the docker repo and link this here? I'll check it out tomorrow / on sunday myself

**Comment by arekkas** [comment]
ok looks like docker-machine is shipped per default. i will probably just introduce an environment variable like `USE_LEGACY_DOCKER=1` which must be used if the old docker toolbox is installed on the system

**Comment by mhurne** [comment]
Nice, thanks @arekkas

**Comment by jefferai** [comment]
I must be missing something but it's not working for me with Docker for Mac. Do I need to be running the v3.0.0 PR?

**Comment by jefferai** [comment]
Apologies. It's working, but apparently it just timed out super badly downloading one of the containers on the first run, so I thought I was still having the same issue!
